# Generated by Django 4.0.6 on 2022-07-05 16:05

from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(max_length=254, upload_to=pictures.models.path_and_rename),
        ),
    ]
